# Generated by Django 4.2.6 on 2023-10-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
    ]
