# Generated by Django 4.2.6 on 2023-10-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0003_rename_autor_post_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
